image: ubuntu:latest

before_install:
  - apt-get update
  - apt-get upgrade -y
  - sudo apt-get install python3-distutils
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - pip3 install -r test-requirements.txt
  - python2 -m pip install -U typing
  - 
script:
  - ls
  - ./runtests.py
  - echo "Done!"
