image: ubuntu:latest

before_install:
  - apt-get update
  - apt-get upgrade -y
  - apt-get install python3-distutils -y
  - apt install curl -y
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py
  - pip3 install -r test-requirements.txt
  - apt install python2 -y
  - curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
  - sudo python2 get-pip.py
script:
  - ls
  - ./runtests.py
  - echo "Done!"
